name: release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: package
      run: ./helper.sh package
    - name: create release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: utils.tar.bz2
        tag: ${{ github.ref }}-${{ GITHUB_SHA }}
        asset_name: bashutils
        overwrite: true

