name: release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set timestamp
      run: echo "RELEASE_TS=$(date +'%y%m%d%H%M%S')" >> ${GITHUB_ENV}
    - name: package
      run: ./helper.sh bashutils package
    - name: create release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bashutils.tar.bz2
        tag: bashutils-${{ env.RELEASE_TS }}
        asset_name: bashutils.tar.bz2
        overwrite: true

