name: release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get timestamp
      id: timestamp
      run: echo "::set-output name=ts::$(date +'%Y%m%d%H%M%S')"
    - name: package
      run: ./helper.sh package
    - name: create release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: utils.tar.bz2
        tag: utils-${{ steps.timestamp.outputs.ts }}
        asset_name: utils.tar.bz2
        overwrite: true

